const listaTareas = require('./tareas')
listaTareas.mostrarTareas()
listaTareas.agregarTareas({description: 'comprar coca', done: true})
listaTareas.agregarTareas({description: 'ir al super', done: true})
listaTareas.agregarTareas({description: 'asda', done: true})
listaTareas.mostrarTareas()
listaTareas.eliminarUnaTarea(2,1)
listaTareas.mostrarTareas()
